  - name: CI Maven
  # You may pin to the exact commit or the version.
  # uses: Best-Quality-Engineering/ci-maven-action@4bc4a4f9a59050271d907afee1ac7f03d171f431
  uses: Best-Quality-Engineering/ci-maven-action@v1.1.0
  with:
    # Specifies parameters used to start up the JVM running Maven
    maven-opts: # optional
    # Produce execution error messages
    errors: # optional, default is true
    # Run in non-interactive (batch) mode (disables output color)
    batch-mode: # optional, default is true
    # Do not display transfer progress when downloading or uploading
    no-transfer-progress: # optional, default is true
    # Only fail the build afterwards; allow all non-impacted builds to continue
    fail-at-end: # optional, default is false
    # Stop at first failure in reactorized builds
    fail-fast: # optional, default is false
    # NEVER fail the build, regardless of project result
    fail-never: # optional, default is false
    # If project list is specified, also build projects required by the list
    also-make: # optional, default is false
    # If project list is specified, also build projects that depend on projects on the list
    also-make-dependents: # optional, default is false
    # Alternate path for the user settings file
    settings-file: # optional
    # Alternate path for the user toolchains file
    toolchains-file: # optional
    # Force the use of an alternate POM file (or directory with pom.xml)
    pom-file: # optional
    # Defines a set of system properties in CSV or multiline format
    system-properties: # optional
    # The CI-friendly revision property to use
    revision: # optional, default is undefined
    # The CI-friendly sha1 property to use
    sha1: # optional, default is undefined
    # The CI-friendly changelist property to use
    changelist: # optional, default is undefined
    # Comma-delimited list of profiles to activate
    profiles: # optional
    # Comma-delimited list of specified reactor projects to build instead of all projects. A project can be specified by [groupId]:artifactId or by its relative path
    projects: # optional
    # Thread count, for instance 2.0C where C is core multiplied
    threads: # optional
    # Comma separated list of goals to execute
    goals: # optional
    # Comma separated list of phases to execute
    phases: # optional
          
